name: denovo_te
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - samtools>=1.15
  - bedtools>=2.30
  - minimap2>=2.24
  - spades>=3.15
  - blast>=2.13
  - r-base>=4.0
  - perl
  - perl-bioperl
